# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-12 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=300, null=True, verbose_name='\u7b54\u6848\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u7b54\u6848',
                'verbose_name_plural': '\u7b54\u6848',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20, null=True, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20, null=True, verbose_name='\u8d44\u6599\u540d\u79f0')),
                ('course_file', models.FileField(upload_to='/files')),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_interface.Course', verbose_name='\u76f8\u5173\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u8d44\u6599',
                'verbose_name_plural': '\u8bfe\u7a0b\u8d44\u6599',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='\u9898\u76ee')),
                ('correct_answer', models.CharField(default=None, max_length=300, null=True, verbose_name='\u6b63\u786e\u7b54\u6848')),
            ],
            options={
                'verbose_name': '\u95ee\u9898',
                'verbose_name_plural': '\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20, null=True, verbose_name='\u4e13\u4e1a')),
            ],
            options={
                'verbose_name': '\u4e13\u4e1a',
                'verbose_name_plural': '\u4e13\u4e1a',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=10, null=True, verbose_name='\u59d3\u540d')),
                ('school_num', models.CharField(default=None, max_length=20, null=True, verbose_name='\u5b66\u53f7')),
                ('password', models.CharField(default=None, max_length=50, null=True, verbose_name='\u5bc6\u7801')),
                ('session', models.CharField(default=None, max_length=50, null=True, verbose_name='\u4f1a\u8bdd\u6570\u636e')),
                ('is_login', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5728\u7ebf')),
                ('course', models.ManyToManyField(to='class_interface.Course', verbose_name='\u9009\u4fee\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u5b66\u751f',
                'verbose_name_plural': '\u5b66\u751f',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_num', models.CharField(default=None, max_length=30, null=True, verbose_name='\u5b66\u5de5\u53f7')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7ec6\u5219',
                'verbose_name_plural': '\u7528\u6237\u7ec6\u5219',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True, verbose_name='\u6d4b\u8bd5\u540d\u79f0')),
                ('is_on', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5f00\u59cb')),
                ('duration', models.IntegerField(default=900, help_text='\u4ee5\u79d2\u4e3a\u5355\u4f4d', verbose_name='\u6d4b\u8bd5\u65f6\u957f')),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_interface.Course', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u6d4b\u8bd5',
                'verbose_name_plural': '\u6d4b\u8bd5',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='test',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_interface.Test', verbose_name='\u6d4b\u8bd5'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='class_interface.TeacherProfile', verbose_name='\u4efb\u8bfe\u8001\u5e08'),
        ),
        migrations.AddField(
            model_name='answer',
            name='problem',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='class_interface.Problem', verbose_name='\u9898\u76ee'),
        ),
    ]
