# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-12 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': '\u8001\u5e08', 'verbose_name_plural': '\u8001\u5e08'},
        ),
        migrations.AddField(
            model_name='answer',
            name='label',
            field=models.CharField(default=None, max_length=1, null=True, verbose_name='\u7b54\u6848\u6240\u5728\u9009\u9879'),
        ),
    ]
