# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-12 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_interface', '0002_auto_20180312_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_number',
            field=models.IntegerField(default=0, null=True, verbose_name='\u9009\u62e9\u6570\u76ee'),
        ),
    ]
