# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_interface', '0003_answer_selected_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sequence',
            field=models.IntegerField(default=1, null=True, verbose_name='\u9898\u76ee\u5e8f\u53f7'),
        ),
    ]
