# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-14 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_interface', '0004_problem_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_img', models.ImageField(upload_to='homework_images/', verbose_name='\u4f5c\u4e1a\u56fe\u7247')),
                ('name', models.CharField(default=None, max_length=300, null=True, verbose_name='\u4f5c\u4e1a\u540d\u79f0')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='class_interface.Student', verbose_name='\u5b66\u751f')),
            ],
            options={
                'verbose_name': '\u4f5c\u4e1a',
                'verbose_name_plural': '\u4f5c\u4e1a',
            },
        ),
    ]
