# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-14 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_interface', '0005_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u7ecf\u6d4b\u8bd5\u8fc7'),
        ),
    ]
